inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7.1
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/javascript/**/*'
    - 'config/environments/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/**/*'
    - 'tmp/**/*'


Metrics/MethodLength:
  Exclude:
    - 'lib/atc/loaders/checksum_loader.rb'
    - 'lib/atc/utils/aws_multipart_checksum_utils.rb'
    - 'lib/atc/aws/s3_uploader.rb'
    - 'lib/atc/utils/aws_checksum_utils.rb'

Rails/Output:
  Exclude:
    - 'lib/atc/aws/s3_uploader.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/atc/aws/s3_uploader.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/atc/aws/s3_uploader.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/atc/aws/s3_uploader.rb'
