inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7.1
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/javascript/**/*'
    - 'config/environments/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Exclude:
    - lib/atc/aip_reader.rb
    - spec/atc/aip_reader_spec.rb

Metrics/AbcSize:
  Exclude:
    - lib/atc/aip_reader.rb

Metrics/ClassLength:
  Exclude:
    - 'lib/atc/aws/remote_fixity_check.rb'

Metrics/MethodLength:
  Exclude:
    - lib/atc/aip_reader.rb
    - 'lib/atc/loaders/checksum_loader.rb'
    - 'lib/atc/utils/aws_multipart_checksum_utils.rb'
    - 'lib/atc/aws/s3_uploader.rb'
    - 'lib/atc/utils/aws_checksum_utils.rb'

Rails/Output:
  Exclude:
    - 'lib/atc/aws/s3_uploader.rb'
    - 'lib/atc/aip_reader.rb'

Lint/MissingCopEnableDirective:
  Enabled: false

