development:
  username: username@email.copm
  password: pass123456789
  domain: cul
  host: host.cul.columbia.edu
  share: folder-to-access

test:
  username: testusername@email.copm
  password: testpass123456789
  domain: cul
  host: testhost.cul.columbia.edu
  share: folder-to-access

